server.port=8080
spring.application.name=cypher-load-analytics

# Cache configuration
spring.cache.cache-names=ethUsdPrices,tokenUsdPrices
spring.cache.caffeine.spec=expireAfterWrite=1h

# Logging
logging.level.root=INFO
logging.level.com.cypher=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Web3j configuration
#web3j.client-address=https://mainnet.base.org

# File simulating load data - useful for demo/testing when RPC is unavailable
load-simulator.enabled=true

# CORS configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*