server.port=8080
spring.application.name=cypher-load-analytics


# Base Chain RPC URL for accessing blockchain data
blockchain.base.rpc-url=https://mainnet.base.org

# Explorer API configuration (optional - for better transaction fetching)
blockchain.base.explorer-api-url=https://api.basescan.org
blockchain.base.explorer-api-key=WNXSTW5WD2TITFH6K7VF4BKFSKV2IVTTRT

# Cache configuration
spring.cache.cache-names=ethUsdPrices,tokenUsdPrices
#TODO : check why cache is not working
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=1h

# Logging
logging.level.root=INFO
logging.level.com.cypher=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Web3j configuration
#web3j.client-address=https://mainnet.base.org

# File simulating load data - useful for demo/testing when RPC is unavailable
load-simulator.enabled=false

# CORS configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

# ------------------------------
# Database Connection Settings
# ------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------------------
# JPA Settings
# ------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# (Optional) Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
